### PR TITLE
Bugfix/unit tests windows 2024

### LINKED ISSUE #1332: JUnit Tests failing after upgrading to 2025.1
After upgrading to 2025.1 our unit tests suddenly stopped working when executed from within the IDE. CI and everything else still works so we suspect it is related to the upgrade of the plugin.

The test code attemts to load test XML files via

```java

private String prepareXXX(String fileName) throws IOException {
        return IOUtils.toString(
                Objects.requireNonNull(this.getClass().getResource("/test/" + fileName)),
                StandardCharsets.UTF_8
        );
    }
```

This always fails even though the test files exist at resources/test/{fileName} in the module root. Do you have an idea, workaround or a potential fix for this?

Thank you!

### PR DESCRIPTION
**Pull request by StefanKruk**
Signed-off-by: Stefan Kruk [stefan.kruk@gmx.net](mailto:stefan.kruk@gmx.net)

### CODE REVIEW

File: src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt [hunk 1]
```diff
@@ -71,6 +72,7 @@ class HybrisJUnitExtension : RunConfigurationExtension() {
                 }
 
                 getTomcatWrapperJVMProperties(tomcatWrapperProperties).forEach {
+                    System.out.println(it)
```
Comment (mlytvyn) [inline src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt]: remove SOUT

File: src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt [hunk 2]
```diff
@@ -26,6 +26,7 @@ import com.intellij.execution.configurations.RunConfigurationBase
 import com.intellij.execution.configurations.RunnerSettings
 import com.intellij.execution.executors.DefaultDebugExecutor
 import com.intellij.execution.junit.JUnitConfiguration
+import com.intellij.idea.plugin.hybris.common.HybrisUtil
```
Comment (mlytvyn) [inline src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt]: remove unused import

**Review by mlytvyn — APPROVED** [review]

File: src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt (hunk 1 above)
Comment (dumko27) [reply src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt]: @StefanKruk

File: src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt (hunk 2 above)
Comment (dumko27) [reply src/com/intellij/idea/plugin/hybris/runConfigurations/HybrisJUnitExtension.kt]: @StefanKruk

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,8 @@
+## [2024.3.8]
```
Comment (dumko27) [inline CHANGELOG.md:1]: @StefanKruk what about 2025.1.2?
Can I expect this fix asap?
