### PR TITLE
Fixed code generation: classpath separator adjusted

### LINKED ISSUE #978: Failure in ProjectBeforeCompilerTask: code is not generated on Win platform
Plugin version: **2023.3.4**

There is following trace in logs:

```
2024-01-30 10:39:15,251 [ 192208] SEVERE - #c.i.c.i.CompileDriver - Error executing task
java.nio.file.InvalidPathException: Illegal char <*> at index 0: *
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.resolve(Path.java:515)
	at com.intellij.idea.plugin.hybris.project.compile.ProjectBeforeCompilerTask.invokeCodeGeneration(ProjectBeforeCompilerTask.kt:112)
	at com.intellij.idea.plugin.hybris.project.compile.ProjectBeforeCompilerTask.execute(ProjectBeforeCompilerTask.kt:84)
	at com.intellij.compiler.impl.CompileDriver.executeCompileTasks(CompileDriver.java:642)
	at com.intellij.compiler.impl.CompileDriver.lambda$startup$5(CompileDriver.java:435)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:155)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### PR DESCRIPTION
**Pull request by yurybich**
Signed-off-by: Yury Bich yury_bich@epam.com

### CODE REVIEW

File: src/com/intellij/idea/plugin/hybris/project/compile/ProjectBeforeCompilerTask.kt [hunk 1]
```diff
@@ -120,7 +120,7 @@ class ProjectBeforeCompilerTask : CompileTask {
             .withParameters(
                 "-Dfile.encoding=UTF-8",
                 "-cp",
-                classpath.joinToString(":"),
+                classpath.joinToString(";"),
```
Comment (mlytvyn) [inline src/com/intellij/idea/plugin/hybris/project/compile/ProjectBeforeCompilerTask.kt]: for Unix it is `:`, please make it OS specific

Comment (yurybich) [reply src/com/intellij/idea/plugin/hybris/project/compile/ProjectBeforeCompilerTask.kt]: Adjusted
