### PR TITLE
Fix the issue #1017

### LINKED ISSUE #1017: exception when executing impex via console
when i try to execute impex from console I get the following exception:

`java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.intellij.idea.plugin.hybris.tools.remote.console.impl.HybrisImpexConsole.getRequestParams(HybrisImpexConsole.kt:98)
	at com.intellij.idea.plugin.hybris.tools.remote.console.impl.HybrisImpexConsole.execute(HybrisImpexConsole.kt:84)
	at com.intellij.idea.plugin.hybris.tools.remote.console.actions.handler.HybrisConsoleExecuteActionHandler$processLine$1$1.run(HybrisConsoleExecuteActionHandler.kt:58)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:132)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:484)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:248)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:248)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:498)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
`

Intellij Ultimate 2023.3.4
SAP Commerce Developer Toolset 2023.3.4
SAP Commerce 2205.21

Intellij and Commerce running in ubuntu WSL

### PR DESCRIPTION
**Pull request by ekalenchuk**

### CODE REVIEW

File: src/com/intellij/idea/plugin/hybris/tools/remote/console/impl/HybrisImpexConsole.kt [hunk 1]
```diff
@@ -95,7 +95,7 @@ class HybrisImpexConsole(project: Project) : HybrisConsole(project, HybrisConsta
             "scriptContent" to query,
             "validationEnum" to importModeComboBox.selectedItem as String,
             "encoding" to "UTF-8",
-            "maxThreads" to maxThreadsSpinner.value as String,
+            "maxThreads" to if (maxThreadsSpinner.value is Int) maxThreadsSpinner.value.toString() else maxThreadsSpinner.value as String,
```
Comment (mlytvyn) [inline src/com/intellij/idea/plugin/hybris/tools/remote/console/impl/HybrisImpexConsole.kt]: `"maxThreads" to maxThreadsSpinner.value.toString(),`

Comment (mlytvyn) [reply src/com/intellij/idea/plugin/hybris/tools/remote/console/impl/HybrisImpexConsole.kt]: #1002 | Fixed request param cast issue for ImpEx execution
